server:
  port: 80
feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18000/eureka/
  instance:
    instance-id: consumer-hystrix #自定义hystrix的相关服务名称信息
    prefer-ip-address: true  #显示ip路径
