spring:
  redis:
    port: 6379
    host: 47.102.85.126
    timeout: 0
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
        min-idle: 0
  devtools:
    restart:
      enabled: true
      trigger-file: devtools.html,devtools.js,devtools.css
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.85.126:3306/logistics?serverTimezone=UTC
    username: logistics
    password: root123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: consumer-server
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 9292
  max-http-header-size: 4048576

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18000/eureka/


#hystrix的超时时间

feign:
  client:
    config:
      remote-service:           #服务名，填写default为所有服务
        connectTimeout: 10000
        readTimeout: 12000
  hystrix:
    enabled: false

