spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///logistics?serverTimezone=UTC
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: consumer-server
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html


server:
  port: 9292

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18000/eureka/

feign:
  hystrix:
    enabled: true  #开启熔断器
  httpclient:
    enabled: true
