server:
  port: 18000
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false         #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false   #false表示不向注册中心注册自己。
    serviceUrl:
      defaultZone: http://localhost:18000/eureka/